export const SWITCH_THREAD = 'SWITCH_THREAD' // 切换标签
export const RECEIVE_ALL = 'RECEIVE_ALL' 
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'
export const ADD_USERNUMBER = 'ADD_USERNUMBER' // 增加用户记数
export const UPDATE_USERNUMBER = 'UPDATE_USERNUMBER'